const data = {
  products: [
    {
      name: 'Premium Dog Food',
      slug: 'premium-dog-food',
      category: 'Dog food',
      image: '/food/food1.jpg',
      price: 50,
      brand: 'Premium Brand',
      flavor: 'Chicken',
      specificUses: ['Healthy Joints', 'Skin and Coat'],
    },
    {
      name: 'Organic Dog Food',
      slug: 'organic-dog-food',
      category: 'Dog food',
      image: '/food/food2.jpg',
      price: 60,
      brand: 'Organic Brand',
      flavor: 'Beef',
      specificUses: ['Healthy Joints', 'Immune System'],
    },
    {
      name: 'Grain-Free Dog Food',
      slug: 'grain-free-dog-food',
      category: 'Dog food',
      image: '/food/food3.jpg',
      price: 70,
      brand: 'Grain-Free Brand',
      flavor: 'Turkey',
      specificUses: ['Skin and Coat', 'Bone Health'],
    },
    {
      name: 'Puppy Dog Food',
      slug: 'puppy-dog-food',
      category: 'Dog food',
      image: '/food/food4.jpg',
      price: 55,
      brand: 'Puppy Brand',
      flavor: 'Lamb',
      specificUses: ['Bone Health', 'Immune System'],
    },
    {
      name: 'Senior Dog Food',
      slug: 'senior-dog-food',
      category: 'senior-dog-food',
      image: '/food/food5.jpg',
      price: 65,
      brand: 'Senior Brand',
      flavor: 'Salmon',
      specificUses: ['Healthy Joints', 'Bone Health'],
    },
    {
      name: 'Hypoallergenic Dog Food',
      slug: 'hypoallergenic-dog-food',
      category: 'Dog food',
      image: '/food/food6.jpg',
      price: 75,
      brand: 'Hypoallergenic Brand',
      flavor: 'Duck',
      specificUses: ['Immune System', 'Skin and Coat'],
    },
    {
      name: 'Weight Control Dog Food',
      slug: 'weight-control-dog-food',
      category: 'Dog food',
      image: '/food/food7.jpg',
      price: 60,
      brand: 'Weight Control Brand',
      flavor: 'Chicken',
      specificUses: ['Healthy Joints', 'Bone Health'],
    },
    {
      name: 'Dental Care Dog Food',
      slug: 'dental-care-dog-food',
      category: 'Dog food',
      image: '/food/food8.jpg',
      price: 70,
      brand: 'Dental Care Brand',
      flavor: 'Mint',
      specificUses: ['Dental Health', 'Immune System'],
    },
    {
      name: 'Rubber Chew Toy',
      slug: 'rubber-chew-toy',
      category: 'Dog Toys',
      image: '/toys/toy1.jpg',
      price: 15,
      brand: 'Rubber Chew Brand',
      flavor: null,
      specificUses: ['Chewing'],
    },
    {
      name: 'Plush Squeaky Toy',
      slug: 'plush-squeaky-toy',
      category: 'Dog Toys',
      image: '/toys/toy2.jpg',
      price: 10,
      brand: 'Plush Squeaky Brand',
      flavor: null,
      specificUses: ['Squeaking'],
    },
    {
      name: 'Rope Tug Toy',
      slug: 'rope-tug-toy',
      category: 'Dog Toys',
      image: '/toys/toy3.jpg',
      price: 12,
      brand: 'Rope Tug Brand',
      flavor: null,
      specificUses: ['Tugging'],
    },
    {
      name: 'Interactive Puzzle Toy',
      slug: 'interactive-puzzle-toy',
      category: 'Dog Toys',
      image: '/toys/toy4.jpg',
      price: 20,
      brand: 'Interactive Puzzle Brand',
      flavor: null,
      specificUses: ['Mental Stimulation'],
    },
    {
      name: 'Ball Launcher',
      slug: 'ball-launcher',
      category: 'Dog Toys',
      image: '/toys/toy5.jpg',
      price: 25,
      brand: 'Ball Launcher Brand',
      flavor: null,
      specificUses: ['Fetch'],
    },
    {
      name: 'Frisbee Toy',
      slug: 'frisbee-toy',
      category: 'Dog Toys',
      image: '/toys/toy6.jpg',
      price: 8,
      brand: 'Frisbee Brand',
      flavor: null,
      specificUses: ['Fetch'],
    },
    {
      name: 'Squeaky Bone Toy',
      slug: 'squeaky-bone-toy',
      category: 'Dog Toys',
      image: '/toys/toy7.jpg',
      price: 11,
      brand: 'Squeaky Bone Brand',
      flavor: null,
      specificUses: ['Squeaking', 'Chewing'],
    },
    {
      name: 'Treat Dispensing Toy',
      slug: 'treat-dispensing-toy',
      category: 'Dog Toys',
      image: '/toys/toy8.jpg',
      price: 18,
      brand: 'Treat Dispensing Brand',
      flavor: null,
      specificUses: ['Dispensing Treats'],
    },
  ],
};

export default data;
