import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/custom/Navbar';
import { StoreProvider } from '@/lib/Store';
const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={inter.className}>
          <Navbar />
          {children}
        </body>
      </html>
    </StoreProvider>
  );
}
